version: '3'

services:
  my-q:
    container_name: mq
    image: rabbitmq:3.8.5-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data: